print("Create a recipe!")
foodName = input("Name a food >")
plantName = input("Name a type of plant >")
cookingMethod = input("Name a method of cooking >")
burntFood = input("What word describes burnt food? >")
diyItem = input("Name a DIY item >")
print()
print("MENU")
print(cookingMethod, foodName, "with", burntFood, plantName, "on a bed of", diyItem)
