print("Getting to know you!")
print()
name = input("What's your name?: ")
favouriteFood = input("What's your favourite food?: ")
favourite_music = input("What's your favourite music?: ")
residence = input("Where do you live?: ")
print()
print("You are\n", name)
print("You're are probably craving for\n", favouriteFood)
print("and chances are you are dancing to\n", favourite_music, "music")
print('living in the calm neighbourhood of\n', residence)
